# Site settings
title: HS Hackers Michigan
location: Michigan
description: "Welcome to the High School Hackers Michigan meetup group!"
baseurl: ""
url: "http://michigan.hshackers.org"

# More settings
accent: "#8e44ad"
twitter: "hshackersmich"
github: "hshackers/michigan"
contact: "contact at victorlourng dot com"
organizers: "Devon Ngo, Abby Walker, and Nick Derrico"

# Get Meetup Notifications, visible or hidden
notifications: "visible"

# Get Meetup Notifications, IFTTT recipie URLs
email: ""
gcal: ""
sms: ""
android: ""
ifttt: "http://ifttt.com/"

# Local Meetup Links
meetup1: "HS Hackers Michigan"
meetup1-url: "https://www.facebook.com/groups/hshackersmichigan/"
meetup2: "Code For Detroit"
meetup2-url: "http://www.codeforamerica.org/governments/detroit"
meetup3: "More Tech Meetups"
meetup3-url: "http://www.meetup.com/find/?allMeetups=false&keywords=technology&radius=25&userFreeform=Michigan&mcId=znull&mcName=Michigan&sort=default"

# Build settings
markdown: kramdown
permalink: pretty
